### ISSUE TITLE
求助大神

### ISSUE THREAD

**Issue by juku8** [kwonganding/wpf.controls#1]
大神您好！
      刚看到这个项目，非常酷炫，谢谢大神的无私！
      我是一个新手，刚下载看了一下，发现自己不会用，呵呵，自己尝试在一个新项目中引用大神的控件，就会显示错误：无效标记。
我的步骤是：
1、先将Util.Controls拷贝到项目同级目录
 2、xaml里添加：xmlns:xly="clr-namespace:Util.Controls;assembly=Util.Controls"  
3、在大神给的Util.Controls.WPFTest复制了一段到xaml里

```
     <StackPanel Height="50">
            <xly:BulletCheckBox />
            <xly:BulletCheckBox Text="不开窍" CheckedText="开启" IsChecked="True" />
            <xly:BulletCheckBox Text="不开窍" CheckedText="开启" IsChecked="True" Height="24"                      Width="60" />
            <xly:BulletCheckBox Height="24" Width="60"/>
        </StackPanel>    
```

经过这三步，发现还是显示

```
 XML 命名空间“clr-namespace:Util.Controls;assembly=Util.Controls”中不存在标记“BulletCheckBox”。 
```

尝试添加引用lib目录下的：System.Utility.dll
如果是anyCPU,会出现处理器架构不匹配的问题
改为X86没问题
但第**3**条里的错误还是存在，无法编译，请大神帮忙！太喜欢这个控件的风格所以想试试，呵呵。

```
  大神能否给新手写一篇如何使用这个控件的教程？step by step，谢谢！
  只要会引用这些控件了就可以看大神给的Util.Controls.WPFTest项目了，再次谢谢！
```

**Comment by kwonganding** [comment]
目前这个组件还不成体系，不是很好的支持第三方使用，主要是提供学习和、独立控件、样式开发。在第二版会考虑。
System.Utility.dll是固定的x86。
问题三，是你没有认真看测试项目的使用方式，不光是xaml使用，还需要引用项目资源，你看看app.xaml代码。

**Comment by sunshengliang** [comment]
谢谢你的代码分享，我的启蒙教程啊
